{% set name = "temporalio" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/temporalio-{{ version }}.tar.gz
  sha256: 932b56720a20401f333ffdaea157cc64d0f9d615a2fd16358bee56d9491bff77

build:
  skip: true  # [py>=400]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - rust
    - poetry-core
    - setuptools
    - wheel
    - setuptools-rust
    - pip
  run:
    - python
    - rust
    - protobuf >=3.20
    - python-dateutil >=2.8.2,<3.0.0  # [py<311]
    - types-protobuf >=3.20
    - typing_extensions >=4.2.0,<5.0.0
  run_constrained:
    - grpcio >=1.59.0,<2.0.0
    - opentelemetry-api >=1.11.1,<2.0.0
    - opentelemetry-sdk >=1.11.1,<2.0.0

test:
  imports:
    - temporalio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/temporalio/sdk-python
  summary: Temporal.io Python SDK
  license: MIT
  license_file:
    - LICENSE
    - temporalio/bridge/sdk-core/LICENSE.txt
    - temporalio/bridge/sdk-core/sdk-core-protos/protos/api_cloud_upstream/LICENSE
    - temporalio/bridge/sdk-core/sdk-core-protos/protos/api_upstream/LICENSE
    - temporalio/bridge/sdk-core/fsm/LICENSE.txt
    - temporalio/bridge/sdk-core/fsm/rustfsm_trait/LICENSE.txt
    - temporalio/bridge/sdk-core/fsm/rustfsm_procmacro/LICENSE.txt

extra:
  recipe-maintainers:
    - jim
